config/routes.rb
STM::Application.routes.draw do
  resources :users
  get "team_member_private_message/new"
  get "team_member_private_message/create"
  get "team_member_private_message/destroy"

  match '/signin',  to: 'sessions#new',         via: 'get'
  resources :player_positions
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :teams do
    resources :events
    resources :team_members
    resources :team_players
    resources :team_coaches
    resources :team_member_availabilities
    resources :team_images
  end
  resources :positions
  resources :team_member_availabilities
  resource :calendar, :only => [:show]

  resources :team_players do
    resources :notes
    resources :player_images
  end
  
  match 'team_players/:id/view_notes', to: 'team_players#view_notes', via: 'get', as: 'view_notes'

  match '/teams/:id/player_positions/:player_id', to: 'teams#player_positions', via: 'get'
  match '/teams/:id/schedule', to: 'teams#schedule', via: 'get', as: 'schedule'
  match '/teams/:id/player_availabilities', to: 'teams#player_availabilities', via: 'get', as: 'availabilities'
  match '/teams/:id/player_stats', to: 'teams#player_stats', via: 'get', as: 'player_stats'
  match '/teams/:id/player_availabilites', to: 'teams#player_availabilities', as: 'player_availabilities', via: 'get'
  match '/teams/:id/member_messages/:member_id', to: 'teams#member_messages', via: 'get'

  match 'TeamMemberCode', to: 'users#team_member_code', via: 'get'
  match 'addUserToMemeber', to: 'team_members#add_user', via: 'post'

  
  match '/team_member_private_message/:id', to: 'team_member_private_message#get_message', via: 'get'

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/login',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :team_member
	belongs_to :team_player
	belongs_to :team_coach
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_filter :get_team_player
  before_filter :return_to

  def return_to
    session[:return_to] ||= request.referer
  end

  def get_team_player
    @team_player = TeamPlayer.find(params[:team_player_id])
  end
  # GET /notes
  def index
    @notes = Note.all
  end

  # GET /notes/1
  def show
    @notes = @team_member.notes
  end

  # GET /notes/new
  def new
    session[:return_to] ||= request.referer
    @team_coach_id = params[:team_coach_id]
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  def create
    @note = @team_player.notes.create(note_params)

    if @note.save
      flash[:success] = 'Note was successfully created.'
      redirect_to session.delete(:return_to)
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /notes/1
  def update

    respond_to do |format|
      if @note.update(note_params)
        format.html
        format.json { respond_with_bip(@note) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@note) }
      end
    end
  end

  # DELETE /notes/1
  def destroy
    @note.destroy
    flash[:success] = 'Not was successfully deleted.'
    redirect_to session.delete(:return_to)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def note_params
    params.require(:note).permit(:note_text, :team_player_id)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for([@team_player, @note]) do |f| %>
  <div class="container">
    <div class="row clearfix">
      <div class="col-md-6 column">
        <div class="panel"><%= f.text_area :note_text, class: "form-control", placeholder:"Note Text"%></div>
      </div>
    </div>
    <div class="row clearfix">
      <div class="col-md-6 column">
        <div class="btn-group">
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>
        <div class="btn-group">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @notes %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<%= render 'form' %>

<%# link_to 'Back', notes_path %>

app/views/notes/new.js.erb
$('#reusableHeading').html("New Note");
$('#reusableBody').html("<%= escape_javascript(render partial: 'form') %>");
$('#reusableFooter').remove();
$('#reusableModal').modal();

app/views/notes/show.html.erb
<%= form_for [@team_member, @notes] do |f| %>
  <% for @notes.each do |note|  %>
    <div class="container">
      <div class="row clearfix">
        <div class="col-md-12 column">
          <div class="row clearfix">
            <div class="col-md-6 column">
              Created:
            </div>
            <div class="col-md-6 column">
            </div>
          </div>
          <div class="jumbotron">
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>