config/routes.rb
STM::Application.routes.draw do
  resources :users
  get "team_member_private_message/new"
  get "team_member_private_message/create"
  get "team_member_private_message/destroy"

  match '/signin',  to: 'sessions#new',         via: 'get'
  resources :player_positions
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :teams do
    resources :events
    resources :team_members
    resources :team_players
    resources :team_coaches
    resources :team_member_availabilities
    resources :team_images
  end
  resources :positions
  resources :team_member_availabilities
  resource :calendar, :only => [:show]

  resources :team_players do
    resources :notes
    resources :player_images
  end
  
  match 'team_players/:id/view_notes', to: 'team_players#view_notes', via: 'get', as: 'view_notes'

  match '/teams/:id/player_positions/:player_id', to: 'teams#player_positions', via: 'get'
  match '/teams/:id/schedule', to: 'teams#schedule', via: 'get', as: 'schedule'
  match '/teams/:id/player_availabilities', to: 'teams#player_availabilities', via: 'get', as: 'availabilities'
  match '/teams/:id/player_stats', to: 'teams#player_stats', via: 'get', as: 'player_stats'
  match '/teams/:id/player_availabilites', to: 'teams#player_availabilities', as: 'player_availabilities', via: 'get'
  match '/teams/:id/member_messages/:member_id', to: 'teams#member_messages', via: 'get'

  match 'TeamMemberCode', to: 'users#team_member_code', via: 'get'
  match 'addUserToMemeber', to: 'team_members#add_user', via: 'post'

  
  match '/team_member_private_message/:id', to: 'team_member_private_message#get_message', via: 'get'

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/login',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :team

  scope :between, lambda {|start_time, end_time|
  where(Event.format_date(start_time) <  Event.format_date(end_time)) }


  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => starts_at.rfc822,
      :end => ends_at.rfc822,
      :allDay => self.all_day,
      :recurring => false,
      :backgroundColor => bgColor

      #:url => Rails.application.routes.url_helpers.team_event_path(self.team, self.id),
      #:color => "red"
    }

  end

  def bgColor
    if self.event_type == 'game'
      'red'
    else
      'blue'
    end
  end

  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :team_member
	belongs_to :team_player
	belongs_to :team_coach
end

app/models/player_image.rb
class PlayerImage < ActiveRecord::Base
		belongs_to :team_player
	mount_uploader :image, PlayerImageUploader
end

app/models/player_position.rb
class PlayerPosition < ActiveRecord::Base
	belongs_to :position
	belongs_to :team_member
	belongs_to :team_player
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :player_positions
	has_many :team_members, through: :player_positions
	has_many :team_players, through: :player_positions
	has_many :team_positions
	has_many :teams, through: :team_positions
end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
    belongs_to :team
    has_many   :event
    belongs_to :team_player
end

app/models/statistics.rb
class Statistics < ActiveRecord::Base
    belongs_to :team
    belongs_to :team_player
    has_many   :event
end

app/models/team.rb
class Team < ActiveRecord::Base

	#attr_accessor :name, :mascot
	validates :name, :mascot, presence: true
	has_many :team_members
	has_many :users, through: :team_members
	has_many :team_member_availabilities, through: :team_members
	has_many :team_players
	has_many :team_coaches
	has_many :notes, through: :team_players
	has_many :team_positions
	has_many :positions, through: :team_positions
	has_many :statistics, through: :team_players
	has_many :events
	has_many :team_images

	include ActiveModel::Conversion
	extend  ActiveModel::Naming
	after_create :add_defaults
	def add_defaults
		self.positions.create(title: 'Goalkeeper')
		self.positions.create(title: 'Midfielder')
		self.positions.create(title: 'Defender')
		self.positions.create(title: 'Forward')
	end
end

app/models/team_coach.rb
class TeamCoach < TeamMember
	belongs_to :team
	has_many :notes
end

app/models/team_image.rb
class TeamImage < ActiveRecord::Base
	belongs_to :team
	mount_uploader :image, TeamPhotoUploader
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
	belongs_to :user
	belongs_to :team
	has_many :player_positions
	has_many :positions, through: :player_positions
	has_many :team_member_availabilities
	has_many :notes
	has_many :team_members
	has_many :statistics
	def self.is_coach
		where(is_coach: 't')
	end

	def full_name
		"#{member_first_name} #{member_last_name}"
	end
end

app/models/team_player.rb
class TeamPlayer < TeamMember
	belongs_to :team
	has_many :notes
	has_many :users, through: :team
	has_many :statistics
	has_many :player_positions
	has_many :positions, through: :player_positions
	has_many :team_member_availabilities
	has_one :player_image
	def position_choices
		self.team.positions
	end

end

app/models/team_position.rb
class TeamPosition < ActiveRecord::Base
	belongs_to :team
	belongs_to :position
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_inclusion_of :user_type, in:Choices['user_type']
	before_save { self.email = email.downcase }
	before_create :create_remember_token

	#removed for testing
	#attr_accessor :first_name, :last_name, :email, :password, :phone_number,
	#				:street_address, :city, :state, :zipcode, :user_type
	#validates :first_name, :last_name, :email, :password, :phone_number,
	#				:street_address, :city, :state, :zipcode, :user_type,
	#				presence: true
	has_many :team_members
	has_many :teams, through: :team_members
	has_secure_password

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	def create_remember_token
		self.remember_token = User.digest(User.new_remember_token)
		self.user_type="member"
	end
end

app/controllers/player_images_controller.rb
class PlayerImagesController < ApplicationController
  before_filter :get_player
  before_filter :return_to

  def return_to
    session[:return_to] ||= request.referer
  end

  def show
    @player_image = PlayerImage.find(params[:id])
  end

  def get_player
    @team_player = TeamPlayer.find(params[:team_player_id])
  end

  def index
    @player_images = @team.player_images
  end

  def new
    @player_image = PlayerImage.new
  end

  def create
    @player_image = PlayerImage.create(player_image_params)

    if @player_image.save
      flash[:success] = "The image has been uploaded."
      redirect_to team_path(@team_player.team)
    else
      render "new"
    end
  end

  def destroy
    @player_image = PlayerImage.find(params[:id])
    @player_image.destroy
    flash[:success] = "The image has been deleted."
    redirect_to team_path(@team)
  end

  private
  def player_image_params
    params.require(:player_image).permit(:team_player_id, :image)
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/player_images_helper.rb
module PlayerImagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/teams_helper.rb
module TeamsHelper

	def is_coach?(team)
		!TeamCoach.where("team_id = ? AND user_id = ?", team, current_user).empty?
	end

	def is_a_coach?(team_member)
		team_member.type == "TeamCoach"
	end

	def has_notes(team_member)
		team_member.notes.count > 0
	end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/player_images/_form.html.erb
<%= form_for [@team_player, @player_image], html: { multipart: true } do |f| %>
  <div class="container">
    <div class="row clearfix">
      <div class="col-md-6 column">
        <div class="panel"><%= f.label "Image File" %>
          <%= f.file_field :image %></div>
      </div>
    </div>
    <div class="row clearfix">
      <div class="col-md-6 column">
        <div class="btn-group">
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>
        <div class="btn-group">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/player_images/_player_image.html.erb
<%= form_for [@team, @team_image] do |f| %>
  <div class="container-fluid">
    <div class="row clearfix">
      <div class="col-md-12 column">
        <%= image_tag @team_image.image, class: "img-responsive img-rounded" %>
      </div>
    </div>
    <div class="row clearfix">
      <div class="col-md-6 column">
        <div class="btn-group">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
        <div class="btn-group">
          <%= link_to 'Delete Image', [@team, @team_image], data:{ confirm: 'Are you sure?'}, method: 'delete', class: 'btn btn-danger' %>
        </div>
      </div>
      <div class="col-md-6 column">
      </div>
    </div>
  </div>
<% end %>

app/views/player_images/edit.html.erb
<h1>Editing player_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_image %> |
<%= link_to 'Back', player_images_path %>

app/views/player_images/index.html.erb
<h1>Listing player_images</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @player_images.each do |player_image| %>
      <tr>
        <td><%= link_to 'Show', player_image %></td>
        <td><%= link_to 'Edit', edit_player_image_path(player_image) %></td>
        <td><%= link_to 'Destroy', player_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player image', new_player_image_path %>

app/views/player_images/new.html.erb
<h1>New player_image</h1>

<%= render 'form' %>

<%= link_to 'Back', player_images_path %>

app/views/player_images/new.js.erb
$('#reusableHeading').remove();
$('#reusableBody').html("<%= escape_javascript(render partial: 'form') %>");
$('#reusableFooter').remove();
$('#reusableModal').modal();

app/views/player_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_player_image_path(@player_image) %> |
<%= link_to 'Back', player_images_path %>

app/views/player_images/show.js.erb
$('#reusableHeading').remove();
$('#reusableBody').html("<%= escape_javascript(render partial: 'player_image') %>");
$('#reusableFooter').remove();
$('#reusableModal').modal();