config/routes.rb
STM::Application.routes.draw do
  resources :users
  get "team_member_private_message/new"
  get "team_member_private_message/create"
  get "team_member_private_message/destroy"

  match '/signin',  to: 'sessions#new',         via: 'get'
  resources :player_positions
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :teams do
    resources :events
    resources :team_members
    resources :team_players
    resources :team_coaches
    resources :team_member_availabilities
    resources :team_images
  end
  resources :positions
  resources :team_member_availabilities
  resource :calendar, :only => [:show]

  resources :team_players do
    resources :notes
    resources :player_images
  end
  
  match 'team_players/:id/view_notes', to: 'team_players#view_notes', via: 'get', as: 'view_notes'

  match '/teams/:id/player_positions/:player_id', to: 'teams#player_positions', via: 'get'
  match '/teams/:id/schedule', to: 'teams#schedule', via: 'get', as: 'schedule'
  match '/teams/:id/player_availabilities', to: 'teams#player_availabilities', via: 'get', as: 'availabilities'
  match '/teams/:id/player_stats', to: 'teams#player_stats', via: 'get', as: 'player_stats'
  match '/teams/:id/player_availabilites', to: 'teams#player_availabilities', as: 'player_availabilities', via: 'get'
  match '/teams/:id/member_messages/:member_id', to: 'teams#member_messages', via: 'get'

  match 'TeamMemberCode', to: 'users#team_member_code', via: 'get'
  match 'addUserToMemeber', to: 'team_members#add_user', via: 'post'

  
  match '/team_member_private_message/:id', to: 'team_member_private_message#get_message', via: 'get'

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/login',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
	belongs_to :user
	belongs_to :team
	has_many :player_positions
	has_many :positions, through: :player_positions
	has_many :team_member_availabilities
	has_many :notes
	has_many :team_members
	has_many :statistics
	def self.is_coach
		where(is_coach: 't')
	end

	def full_name
		"#{member_first_name} #{member_last_name}"
	end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :edit, :update, :destroy]
  before_filter :get_team, except: :view_notes
  # GET /team_members

  def get_team
    @team = Team.find(params[:team_id])
  end

  def view_notes
    @team_member = TeamMember.find(params[:id])
    @team_player = @team_member
    @notes = @team_member.notes
  end

  def index
    @team_members = TeamMember.all
  end

  # GET /team_members/1
  def show
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
    @team_adding_id = params[:team_id]
  end

  # GET /team_members/1/edit
  def edit
    @team_member = TeamMember.find(params[:id])
    # @notes = Note.find_by_player_id(@team_member)
    @user_id = @team_member.user_id
    @team_id = @team_member.team_id
  end


  # POST /team_members
  def create
    @team_member = @team.team_members.create(team_member_params)

    if @team_member.save
      # redirect_to @team_member, notice: 'Team member was successfully created.'
      flash[:success] = 'Team member was successfully created.'
      redirect_to @team
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /team_members/1
  def update
    @team_member.attributes = {'position_ids' => []}.merge(params[:team_member] || {})
    if @team_member.update(team_member_params)
      redirect_to @team_member, notice: 'Team member was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /team_members/1
  def destroy
    @team_member.destroy
    redirect_to team_members_url, notice: 'Team member was successfully destroyed.'
  end

  def note
    @team_member = TeamMember.find(params[:id])
    @notes = @team_member.notes
  end

  def add_user
    # TODO: Add error checking to this code and fix the redirects
    @team_member = TeamMember.find(params[:team_member][:code])
    @team_member.user_id = current_user.id
    if @team_member.update(team_member_params)
      redirect_to root_path, notice: 'Team member was successfully updated.'
    else
      redirect_to :Back, notice: 'Team member was not successfully updated.'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_team_member
    @team_member = TeamMember.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def team_member_params
    params.require(:team_member).permit(:user_id, :team_id, :member_first_name, :member_last_name, :notes)
  end

end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_form.html.erb
<style>
body .modal {
  /* new custom width */
  width: 500px;
  /* must be half of the width, minus scrollbar on the left (30px) */
  margin-left: -250px;
}
input {
  width: 457px;
}
</style>

<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="text-center">New Team Member</h1>
      </div>
      <div class="modal-body">
        <%= form_for(@team_member,  html: { class: "form col-md-12" }, url: team_members_path) do |f| %>
          <% if @team_member.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@team_member.errors.count, "error") %> prohibited this team member from being saved:</h2>
              <ul>
                <% @team_member.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= f.hidden_field :team_id, :value => @team_adding_id%>
          <div class="form-group">
            <%= f.text_field :member_first_name , class: "form-control input-lg", placeholder:"First name"%>
          </div>
          <div class="form-group">
            <%= f.text_field :member_last_name , class: "form-control input-lg", placeholder:"Last name"%>
          </div>
          <div class="form-group" >
            <%= f.submit "Create Team Member", class: "btn btn-primary" %>
            <%= link_to 'Back', profile_path(id: @team_adding_id), class: "btn pull-right" %>
          </div>
       <% end %>
     </div>
   </div>
 </div>
</div>

app/views/team_members/_note.html.erb
<style>
  body .modal {
    /* new custom width */
    width: 500px;
    /* must be half of the width, minus scrollbar on the left (30px) */
    margin-left: -250px;
  }
  input {
    width: 457px;
  }
</style>
<div id="notes-modal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="text-center">Player Notes</h1>
      </div>
      <div class="modal-body">
        <%= form_for @team_member do |f| %>
          <form class="form col-md-12">
            <table id="notes_table" class="table table-hover">
              <thead>
                <tr>
                  <th>Notes</th>
                </tr>
              </thead>
              <tbody>
                <% @team_member.notes.each do |note| %>
                  <tr>
                    <td><%= note.note_text %></td>
                    <td><div class="btn btn-xs">Edit</div>
                      <div class="btn btn-xs">Delete</div></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </form>
        <% end %>
      </div>
      <div class="modal-footer">
        <a class="btn pull-left" href="#">Add New Note</a>
        <%= submit_tag 'Close', :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal", "aria-hidden" => "true" %>
      </div>
    </div>
  </div>
</div>

app/views/team_members/_team_member.html.erb
<%= form_for([@team, @team_member]) do |f| %>
  <div class="field">
      <%= f.label "First Name" %>
      <%= f.text_field :member_first_name , class: "form-control input-lg", placeholder:"First name"%>
  </div>
  <div class="field">
      <%= f.label "Last Name" %>
      <%= f.text_field :member_last_name , class: "form-control input-lg", placeholder:"Last name"%>
  <div>
  <div class="actions">
    <%= f.submit "Create Team Member", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/team_members/edit.html.erb
<% provide(:title, "Edit team member") %>
<h1>Edit team member information</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :member_first_name %>
      <%= f.text_field :member_first_name %>

      <%= f.label :member_last_name %>
      <%= f.text_field :member_last_name %>

      <%= f.label :type %>
      <%= f.text_field :type %>

      <%= f.label :user_id %>
      <%= f.text_field :user_id %>

      <%= f.label :team_id %>
      <%= f.text_field :team_id %>

      <%= f.label :updated_at %>
      <%= f.text_field :updated_at %>

      <%= f.label :created_at %>
      <%= f.text_field :created_at %>

      <%= link_to 'Edit player positions', teams_profile_path %> 

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    
  </div>
</div>

<%= link_to 'Show', @team_member %> |
<%= link_to 'Back', team_members_path %>

app/views/team_members/edit_notes.html.erb
<%= form_for(@team_member) do |f| %>
  <% if @team_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :fnotes %>
  </div>
<% end %>

app/views/team_members/index.html.erb
<h1>Listing team_members</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @team_members.each do |team_member| %>
      <tr>
        <td><%= link_to 'Show', team_member %></td>
        <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
        <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team member', new_team_member_path %>

app/views/team_members/new.js.erb
$('#reusableHeading').html("New Team Member");
$('#reusableBody').html("<%= escape_javascript(render @team_member) %>");
$('#reusableFooter').remove();
$('#reusableModal').modal();

app/views/team_members/note.js.erb
$("#view-notes-modal").html("<%= escape_javascript(render 'note') %>");
$('#view-notes-modal').modal('show')

app/views/team_members/notes.html.erb
<style>
    body .modal {
        /* new custom width */
        width: 500px;
        /* must be half of the width, minus scrollbar on the left (30px) */
        margin-left: -250px;
    }
    input {
        width: 457px;
    }
</style>
<%= form_for @team_member do |f| %>
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="text-center">Login</h1>
            </div>
            <div class="modal-body">
                <form class="form col-md-12">
                    <div class="form-group">
                        <%= f.text_area :notes %>  
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control input-lg" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <a class="btn btn-primary" href="#">Sign In</a>
                        <a class="btn pull-right" href="#">Register</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/team_members/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_team_member_path(@team_member) %> |
<%= link_to 'Back', team_members_path %>