config/routes.rb
STM::Application.routes.draw do
  resources :users
  get "team_member_private_message/new"
  get "team_member_private_message/create"
  get "team_member_private_message/destroy"

  match '/signin',  to: 'sessions#new',         via: 'get'
  resources :player_positions
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :teams do
    resources :events
    resources :team_members
    resources :team_players
    resources :team_coaches
    resources :team_member_availabilities
    resources :team_images
  end
  resources :positions
  resources :team_member_availabilities
  resource :calendar, :only => [:show]

  resources :team_players do
    resources :notes
    resources :player_images
  end
  
  match 'team_players/:id/view_notes', to: 'team_players#view_notes', via: 'get', as: 'view_notes'

  match '/teams/:id/player_positions/:player_id', to: 'teams#player_positions', via: 'get'
  match '/teams/:id/schedule', to: 'teams#schedule', via: 'get', as: 'schedule'
  match '/teams/:id/player_availabilities', to: 'teams#player_availabilities', via: 'get', as: 'availabilities'
  match '/teams/:id/player_stats', to: 'teams#player_stats', via: 'get', as: 'player_stats'
  match '/teams/:id/player_availabilites', to: 'teams#player_availabilities', as: 'player_availabilities', via: 'get'
  match '/teams/:id/member_messages/:member_id', to: 'teams#member_messages', via: 'get'

  match 'TeamMemberCode', to: 'users#team_member_code', via: 'get'
  match 'addUserToMemeber', to: 'team_members#add_user', via: 'post'

  
  match '/team_member_private_message/:id', to: 'team_member_private_message#get_message', via: 'get'

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/login',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'

end

app/models/team_member_availability.rb
class TeamMemberAvailability < ActiveRecord::Base
  belongs_to :team_member
  belongs_to :team_player
  

end

app/controllers/team_member_availabilities_controller.rb
class TeamMemberAvailabilitiesController < ApplicationController
  before_action :set_team_member_availability, only: [:update, :edit, :destroy]
  before_action :get_team_player, only: [:new]

  def get_team_player
    @team_player = TeamMember.find(params[:team_player_id])
  end

  def new
    @team_member_availability = TeamMemberAvailability.new
    @team = Team.find(@team_player.team_id)
  end

  def create
    @team_member_availability = TeamMemberAvailability.new(team_member_availability_params)

    # Haven't decided how correctly to finish this
    if @team_member_availability.save
      redirect_to :back, notice: 'Availability was successfully added.'
    else
      redirect_to :back, notice: 'Availability was not added.'
    end
  end

  def update
    # Haven't decided how corectly to finish this
    if @team_member_availability.update(team_member_availability_params)
      redirect_to @team_player, notice: 'Availability was successfully updated.'
    else
      redirect_to @team_player, notice: 'Availability was not updated.'
    end
  end

  def edit
  end

  def destroy
    if params.has_key?(:team_member_availability)
      TeamAvailabilities.find_by_id(params[:team_position]).destroy
      redirect_to :back, notice: "Availability successfully deleted!"
    else
      @team_member_availability.destroy
      redirect_to teams_url, notice: 'Availability successfully destroyed.'
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_team_member_availability
    @team_member_availability = TeamMemberAvailability.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def team_member_availability_params
    params.require(:team_member_availability).permit( :isAvailable, :from, :till, :team_player_id)
  end
end

app/helpers/team_member_availability_helper.rb
module TeamMemberAvailabilityHelper

end

app/views/team_member_availabilities/_form.html.erb
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="text-center">Edit Availabilities</h1>
      </div>
      <div class="modal-header">
        <div class="text-center">
          <strong>
            <%= @team_player.member_first_name %>
            <%= @team_player.member_last_name %>
          </strong>
        </div>
      </div>
      <div class="modal-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Availability</th>
              <th>Date/Time</th>
            </tr>
          </thead>
          <tbody>
            <% @team_player.team_member_availabilities.each do |availability| %>
              <tr>
                <%# Availability %>
                <th>
                  <% if availability.isAvailable? %>
                    Available
                  <% else %>
                    Unavailable
                  <% end %>
                </th>
                <%# Date/Time %>
                <th>
                  <%= "#{availability.from.to_formatted_s(:short)} - #{availability.till.to_formatted_s(:short)}" %>
                </th>
                <%# Delete %>
                <th>
                  <%= link_to 'Delete', availability,
                    :confirm => 'Are you sure?', :method => :delete, class: "btn pull-right" %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-header">
        <div class="text-center">
          <strong>
            New Availability
          </strong>
        </div>
      </div>
      <div class="modal-body">
        <%= form_for(:team_member_availability, url: team_member_availabilities_path) do |f| %>
          <div class="form-group">
            <%= f.hidden_field :team_player_id, :value => @team_player.id %>
          </div>
          <div class="form-group">
            <p>Check if you are available:
              <%= f.check_box :isAvailable, class: "form-control input-lg" %></p>
          </div>
          <div class="form-group">
            <%# f.time_field :from_time , class: "form-control input-lg", placeholder:"hh:mm"%>
            <%= f.label "From:" %>
            <%= f.datetime_select :from, :minute_step => 15 %>
          </div>
          <div class="form-group">
            <%# f.time_field :till_time , class: "form-control input-lg", placeholder:"hh:mm"%>
            <%= f.label "Till:" %>
            <%= f.datetime_select :till, :minute_step => 15 %>
          </div>
          <div class="form-group" >
            <%= f.submit "Set Availability", class: "btn btn-secondary" %>
          </div>
        <% end %>
        <%= link_to 'Done', player_availabilities_path(id: @team.id), class: "btn btn-primary btn-block link-btn-text-white" %>
      </div>
    </div>
  </div>
</div>

app/views/team_member_availabilities/create.html.erb
<h1>TeamMemberAvailability#create</h1>
<p>Find me in app/views/team_member_availability/create.html.erb</p>

app/views/team_member_availabilities/destroy.html.erb
<h1>TeamMemberAvailability#destroy</h1>
<p>Find me in app/views/team_member_availability/destroy.html.erb</p>

app/views/team_member_availabilities/edit.html.erb
<%= render 'form' %>

app/views/team_member_availabilities/new.html.erb
<%= render 'form' %>

app/views/team_member_availabilities/update.html.erb
<%= render 'form' %>